feat: allows to propagete providers named reset to its dependents
young-steveo/bottlejs pull request #196
Opened 2023-09-22 22:29 UTC by esroyo

This PR implements the ideas proposed on issue https://github.com/young-steveo/bottlejs/issues/193

@young-steveo I think the most "notable" change, is that It is no longer possible to configure the final instance as a direct `value` in the property descriptor. Regardless of the existence of middleware, the getter is needed to keep track of the accesses to the container.

Although that is an "internal detail", that fact could be relevant enough to represent a major version bump.

Changes to the README are fairly minimal; awaiting for your feedback before investing more work. Thanks!

2023-11-15 18:03 UTC, young-steveo requested changes
This looks good! I added a couple of comments.  Also, could you elaborate on

> It is no longer possible to configure the final instance as a direct value in the property descriptor

I'm not sure I follow.

2023-11-22 20:06 UTC, esroyo commented on src/Bottle/middleware.js
> +            }
That would be cool! Unfortunately it does not seem possible with the current `middleware` signature, as It does not give access to the `name` of the service being accessed (just the instance). Without the name It is not possible to push the captureTarget into that dependents[name] list...

2023-11-22 20:27 UTC, esroyo commented on test/spec/provider.spec.js
> +            expect(b.container.Thing.In.Something instanceof ThingProvider).toBe(true);
This is actually a tangential fix included in the changed code.

If you try to make this exact change in tests for the current `master`, you will see that it fails with more than one level deepness. Thus the change in the test description from `allows for sub containers to re-initiate as well` to `allows for deep sub containers to re-initiate as well`. I could keep the old one as-is, and add this new test with the sub sub container case :)

2023-11-22 20:34 UTC, esroyo commented
> > It is no longer possible to configure the final instance as a direct value in the property descriptor
> 
> I'm not sure I follow.

I was alluding to the elimination of the possibility to configure `value` in the property descriptor here: https://github.com/young-steveo/bottlejs/pull/196/files#diff-fdb247437fd68a61581f78513f2d7b710cfc757b6288e57cfee6e9182d8678fcL30
We would need to go always via the getter function, which in the end is an extra function call for cases when there is no middleware.

2023-12-21 22:36 UTC, young-steveo commented
I'm going to call it good.  I'm unsure if this requires a major version bump, but I'll investigate before figuring out which version to deploy.

Thanks for all your work!

2023-12-21 22:36 UTC, merged

2024-02-08 15:22 UTC, esroyo commented
> I'm going to call it good. I'm unsure if this requires a major version bump, but I'll investigate before figuring out which version to deploy.
> 
> Thanks for all your work!

My two cents about the version bump:
- technically this is a clean API addition and would fit in a minor bump.
- changing a function from one param to two in JS is always delicate. There is a risk that someone has been passing around the function in callback style to Array prototype methods, which usually work nice with one param functions but can introduce mysterious behaviours when using more than one param (typical `Array#map(parseInt)` problem). Probably not the case for `resetProviders`, but you never know.
- Given the chances of this package being used on relatively old or stable code bases, I would opt for a major bump to ensure no risk of unintentional upgrades on those code bases.

I'm grateful to have the opportunity to contribute to this little piece of software, which I have used so much. Thanks to you @young-steveo for the original creation and for keeping this package alive during all this years.

Best regards.